/**
 * Session Manager for stateful Streamable HTTP MCP transport.
 *
 * Each client session owns a StreamableHTTPServerTransport + McpServer pair.
 * Sessions are identified by mcp-session-id header (generated by the SDK).
 * Notifications are broadcast to all active sessions via their McpServer instances.
 */

import type { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { logger, LOG_MODULES } from '@utils/logger/index.js';
import { getGatewayDebugSetting } from '@utils/json-utils.js';

interface SessionState {
  sessionId: string;
  transport: StreamableHTTPServerTransport;
  server: McpServer;
  createdAt: number;
  lastAccessedAt: number;
  isClosing: boolean;
  activeSseCount: number;
}

const SESSION_TIMEOUT_MS = 10 * 60 * 1000; // 10 minutes
const CLEANUP_INTERVAL_MS = 60 * 1000; // every minute

export class SessionManager {
  private sessions = new Map<string, SessionState>();
  private cleanupTimer: ReturnType<typeof setInterval> | null = null;

  /**
   * Registers a newly created session.
   */
  addSession(sessionId: string, transport: StreamableHTTPServerTransport, server: McpServer): void {
    this.sessions.set(sessionId, {
      sessionId,
      transport,
      server,
      createdAt: Date.now(),
      lastAccessedAt: Date.now(),
      isClosing: false,
      activeSseCount: 0
    });
    if (getGatewayDebugSetting()) {
      logger.debug(
        `Session registered: ${sessionId} (total: ${this.sessions.size}, activeSseCount: 0)`,
        LOG_MODULES.GATEWAY
      );
    }
    this.ensureCleanupTimer();
  }

  /**
   * Looks up an existing session by ID and updates lastAccessedAt.
   */
  getSession(sessionId: string): SessionState | undefined {
    const session = this.sessions.get(sessionId);
    if (session && !session.isClosing) {
      session.lastAccessedAt = Date.now();
      return session;
    }
    return undefined;
  }

  /**
   * Marks an SSE stream as opened for the given session.
   * Prevents the session from being cleaned up while the stream is active.
   */
  markSseOpened(sessionId: string): void {
    const session = this.sessions.get(sessionId);
    if (session && !session.isClosing) {
      session.activeSseCount++;
      if (getGatewayDebugSetting()) {
        logger.debug(
          `Session ${sessionId} SSE opened (activeSseCount: ${session.activeSseCount})`,
          LOG_MODULES.GATEWAY
        );
      }
    }
  }

  /**
   * Marks an SSE stream as closed for the given session.
   */
  markSseClosed(sessionId: string): void {
    const session = this.sessions.get(sessionId);
    if (session) {
      session.activeSseCount = Math.max(0, session.activeSseCount - 1);
      if (getGatewayDebugSetting()) {
        logger.debug(
          `Session ${sessionId} SSE closed (activeSseCount: ${session.activeSseCount})`,
          LOG_MODULES.GATEWAY
        );
      }
    }
  }

  /**
   * Removes a session (called on DELETE or onsessionclosed).
   */
  removeSession(sessionId: string): void {
    const session = this.sessions.get(sessionId);
    if (!session || session.isClosing) return;
    session.isClosing = true;
    try {
      session.transport.close().catch((err) => {
        logger.debug(
          `Error closing transport for session ${sessionId}: ${err}`,
          LOG_MODULES.GATEWAY
        );
      });
    } catch {
      // transport may already be closed
    }
    this.sessions.delete(sessionId);
    if (getGatewayDebugSetting()) {
      logger.debug(
        `Session removed: ${sessionId} (total: ${this.sessions.size}, age: ${Date.now() - session.createdAt}ms, activeSseCount: ${session.activeSseCount})`,
        LOG_MODULES.GATEWAY
      );
    }
  }

  /**
   * Broadcasts a notification to all active sessions.
   * @param method - 'tools' for sendToolListChanged, 'resources' for sendResourceListChanged
   */
  broadcastNotification(method: 'tools' | 'resources'): void {
    if (this.sessions.size === 0) return;
    for (const [sessionId, state] of this.sessions) {
      if (state.isClosing) continue;
      try {
        if (method === 'tools') {
          state.server.sendToolListChanged();
        } else {
          state.server.sendResourceListChanged();
        }
      } catch (error) {
        logger.debug(
          `Failed to broadcast ${method} notification to session ${sessionId}: ${error}`,
          LOG_MODULES.GATEWAY
        );
      }
    }
  }

  /**
   * Removes sessions that have been idle longer than SESSION_TIMEOUT_MS.
   */
  private cleanupStaleSessions(): void {
    const now = Date.now();
    const staleIds: string[] = [];
    let skippedClosing = 0;
    let skippedSse = 0;
    for (const [id, state] of this.sessions) {
      if (state.isClosing) {
        skippedClosing++;
        continue;
      }
      if (state.activeSseCount > 0) {
        skippedSse++;
        continue;
      }
      if (now - state.lastAccessedAt > SESSION_TIMEOUT_MS) {
        staleIds.push(id);
      }
    }
    if (getGatewayDebugSetting() && (staleIds.length > 0 || skippedSse > 0)) {
      logger.debug(
        `Stale cleanup: total=${this.sessions.size} stale=${staleIds.length} skippedClosing=${skippedClosing} skippedSse=${skippedSse}`,
        LOG_MODULES.GATEWAY
      );
    }
    for (const id of staleIds) {
      logger.info(`Removing stale session: ${id}`, LOG_MODULES.GATEWAY);
      this.removeSession(id);
    }
  }

  private ensureCleanupTimer(): void {
    if (this.cleanupTimer) return;
    this.cleanupTimer = setInterval(() => this.cleanupStaleSessions(), CLEANUP_INTERVAL_MS);
    this.cleanupTimer.unref();
  }

  /**
   * Shuts down all sessions. Called on server shutdown.
   */
  shutdownAll(): void {
    if (this.cleanupTimer) {
      clearInterval(this.cleanupTimer);
      this.cleanupTimer = null;
    }
    for (const [id] of this.sessions) {
      this.removeSession(id);
    }
    logger.info('All sessions shut down', LOG_MODULES.GATEWAY);
  }

  /** Returns the current session count (for diagnostics). */
  get sessionCount(): number {
    return this.sessions.size;
  }
}

/** Singleton instance. */
export const sessionManager = new SessionManager();
