/**
 * Session Manager for stateful Streamable HTTP MCP transport.
 *
 * Each client session owns a StreamableHTTPServerTransport + McpServer pair.
 * Sessions are identified by mcp-session-id header (generated by the SDK).
 * Notifications are broadcast to all active sessions via their McpServer instances.
 */

import type { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { logger, LOG_MODULES } from '@utils/logger/index.js';
import { getGatewayDebugSetting } from '@utils/json-utils.js';
import { configManager } from '@config/config-manager.js';

interface SessionState {
  sessionId: string;
  transport: StreamableHTTPServerTransport;
  server: McpServer;
  createdAt: number;
  lastAccessedAt: number;
  isClosing: boolean;
  activeSseCount: number;
  lastPingedAt: number;
  pingPending: boolean;
  clientName?: string;
  clientVersion?: string;
  protocolVersion?: string;
  createdByMethod?: string;
  lastMethod?: string;
}

const CLEANUP_INTERVAL_MS = 60 * 1000; // every minute
const PING_COOLDOWN_MS = 30 * 1000; // min interval between pings
const PING_TIMEOUT_MS = 10 * 1000; // per-ping timeout

export class SessionManager {
  private sessions = new Map<string, SessionState>();
  private cleanupTimer: ReturnType<typeof setInterval> | null = null;

  private pendingClientMetadata = new WeakMap<
    McpServer,
    { clientName: string; clientVersion: string; protocolVersion: string }
  >();

  /**
   * Registers a newly created session.
   */
  addSession(sessionId: string, transport: StreamableHTTPServerTransport, server: McpServer): void {
    const pendingMeta = this.pendingClientMetadata.get(server);
    this.pendingClientMetadata.delete(server);

    this.sessions.set(sessionId, {
      sessionId,
      transport,
      server,
      createdAt: Date.now(),
      lastAccessedAt: Date.now(),
      isClosing: false,
      activeSseCount: 0,
      lastPingedAt: 0,
      pingPending: false,
      clientName: pendingMeta?.clientName,
      clientVersion: pendingMeta?.clientVersion,
      protocolVersion: pendingMeta?.protocolVersion,
      createdByMethod: 'POST',
      lastMethod: 'POST'
    });
    if (getGatewayDebugSetting()) {
      logger.debug(
        `Session registered: ${sessionId} (total: ${this.sessions.size}, activeSseCount: 0)`,
        LOG_MODULES.GATEWAY
      );
    }
    this.ensureCleanupTimer();
  }

  /**
   * Looks up an existing session by ID and updates lastAccessedAt.
   */
  getSession(sessionId: string): SessionState | undefined {
    const session = this.sessions.get(sessionId);
    if (session && !session.isClosing) {
      session.lastAccessedAt = Date.now();
      return session;
    }
    return undefined;
  }

  /**
   * Marks an SSE stream as opened for the given session.
   * Prevents the session from being cleaned up while the stream is active.
   */
  markSseOpened(sessionId: string): void {
    const session = this.sessions.get(sessionId);
    if (session && !session.isClosing) {
      session.activeSseCount++;
      if (getGatewayDebugSetting()) {
        logger.debug(
          `Session ${sessionId} SSE opened (activeSseCount: ${session.activeSseCount})`,
          LOG_MODULES.GATEWAY
        );
      }
    }
  }

  /**
   * Marks an SSE stream as closed for the given session.
   */
  markSseClosed(sessionId: string): void {
    const session = this.sessions.get(sessionId);
    if (session) {
      session.activeSseCount = Math.max(0, session.activeSseCount - 1);
      if (getGatewayDebugSetting()) {
        logger.debug(
          `Session ${sessionId} SSE closed (activeSseCount: ${session.activeSseCount})`,
          LOG_MODULES.GATEWAY
        );
      }
    }
  }

  /**
   * Removes a session (called on DELETE or onsessionclosed).
   */
  removeSession(sessionId: string): void {
    const session = this.sessions.get(sessionId);
    if (!session || session.isClosing) return;
    session.isClosing = true;
    try {
      session.transport.close().catch((err) => {
        logger.debug(
          `Error closing transport for session ${sessionId}: ${err}`,
          LOG_MODULES.GATEWAY
        );
      });
    } catch {
      // transport may already be closed
    }
    this.sessions.delete(sessionId);
    if (getGatewayDebugSetting()) {
      logger.debug(
        `Session removed: ${sessionId} (total: ${this.sessions.size}, age: ${Date.now() - session.createdAt}ms, activeSseCount: ${session.activeSseCount})`,
        LOG_MODULES.GATEWAY
      );
    }
  }

  private pendingBroadcasts = new Map<string, ReturnType<typeof setTimeout>>();
  private readonly BROADCAST_DEBOUNCE_MS = 3000;

  /**
   * Broadcasts a notification to all active sessions.
   * Debounced: same-type notifications within BROADCAST_DEBOUNCE_MS are coalesced.
   * @param method - 'tools' for sendToolListChanged, 'resources' for sendResourceListChanged
   */
  broadcastNotification(method: 'tools' | 'resources'): void {
    // Skip if a debounce timer for this method type is already pending
    if (this.pendingBroadcasts.has(method)) return;

    this.pendingBroadcasts.set(
      method,
      setTimeout(() => {
        this.pendingBroadcasts.delete(method);
        if (this.sessions.size === 0) return;
        for (const [sessionId, state] of this.sessions) {
          if (state.isClosing) continue;
          try {
            if (method === 'tools') {
              state.server.sendToolListChanged();
            } else {
              state.server.sendResourceListChanged();
            }
          } catch (error) {
            logger.debug(
              `Failed to broadcast ${method} notification to session ${sessionId}: ${error}`,
              LOG_MODULES.GATEWAY
            );
          }
        }
      }, this.BROADCAST_DEBOUNCE_MS)
    );
  }

  /**
   * Removes sessions that have been idle longer than SESSION_TIMEOUT_MS.
   */
  private cleanupStaleSessions(): void {
    const now = Date.now();
    const staleIds: string[] = [];
    let skippedClosing = 0;
    let skippedSse = 0;
    let pingFailed = 0;

    for (const [id, state] of this.sessions) {
      if (state.isClosing) {
        skippedClosing++;
        continue;
      }
      // Ping from last cycle timed out — session is dead
      if (state.pingPending) {
        state.pingPending = false;
        pingFailed++;
        staleIds.push(id);
        continue;
      }
      if (state.activeSseCount > 0) {
        if (now - state.lastPingedAt < PING_COOLDOWN_MS) {
          skippedSse++;
          continue;
        }
        state.lastPingedAt = now;
        state.pingPending = true;
        // Fire-and-forget concurrent ping with timeout
        const pingWithTimeout = Promise.race([
          state.server.server.ping(),
          new Promise<never>((_, reject) =>
            setTimeout(() => reject(new Error('Ping timeout')), PING_TIMEOUT_MS)
          )
        ]);
        pingWithTimeout.then(
          () => {
            const s = this.sessions.get(id);
            if (s) {
              s.pingPending = false;
              s.lastAccessedAt = Date.now();
            }
          },
          () => {
            // Keep pingPending=true so the next cycle cleans up this dead session
          }
        );
        skippedSse++;
        continue;
      }
      if (now - state.lastAccessedAt > configManager.getConfig().security.idleConnectionTimeout) {
        staleIds.push(id);
      }
    }

    if (getGatewayDebugSetting() && (staleIds.length > 0 || skippedSse > 0 || pingFailed > 0)) {
      logger.debug(
        `Stale cleanup: total=${this.sessions.size} stale=${staleIds.length} skippedClosing=${skippedClosing} skippedSse=${skippedSse} pingFailed=${pingFailed}`,
        LOG_MODULES.GATEWAY
      );
    }
    for (const id of staleIds) {
      logger.info(`Removing stale session: ${id}`, LOG_MODULES.GATEWAY);
      this.removeSession(id);
    }
  }

  private ensureCleanupTimer(): void {
    if (this.cleanupTimer) return;
    this.cleanupTimer = setInterval(() => this.cleanupStaleSessions(), CLEANUP_INTERVAL_MS);
    this.cleanupTimer.unref();
  }

  /**
   * Shuts down all sessions. Called on server shutdown.
   */
  shutdownAll(): void {
    if (this.cleanupTimer) {
      clearInterval(this.cleanupTimer);
      this.cleanupTimer = null;
    }
    for (const timer of this.pendingBroadcasts.values()) {
      clearTimeout(timer);
    }
    this.pendingBroadcasts.clear();
    for (const [id] of this.sessions) {
      this.removeSession(id);
    }
    logger.info('All sessions shut down', LOG_MODULES.GATEWAY);
  }

  /** Returns the current session count (for diagnostics). */
  get sessionCount(): number {
    return this.sessions.size;
  }

  /**
   * Stores client metadata against a McpServer instance so that
   * addSession() can consume it when the session is registered later.
   */
  storePendingClientMetadata(
    server: McpServer,
    metadata: { clientName: string; clientVersion: string; protocolVersion: string }
  ): void {
    this.pendingClientMetadata.set(server, metadata);
  }

  /**
   * Returns metadata for all active sessions. Does not expose internal
   * transport or server references.
   */
  getAllSessions(): Array<{
    sessionId: string;
    clientName?: string;
    clientVersion?: string;
    protocolVersion?: string;
    createdByMethod?: string;
    lastMethod?: string;
    createdAt: string;
    lastAccessedAt: string;
    isClosing: boolean;
    activeSseCount: number;
  }> {
    const result: ReturnType<SessionManager['getAllSessions']> = [];
    for (const state of this.sessions.values()) {
      result.push({
        sessionId: state.sessionId,
        clientName: state.clientName,
        clientVersion: state.clientVersion,
        protocolVersion: state.protocolVersion,
        createdByMethod: state.createdByMethod,
        lastMethod: state.lastMethod,
        createdAt: new Date(state.createdAt).toLocaleString(),
        lastAccessedAt: new Date(state.lastAccessedAt).toLocaleString(),
        isClosing: state.isClosing,
        activeSseCount: state.activeSseCount
      });
    }
    return result;
  }

  /** Updates the last HTTP method seen for a session. */
  updateSessionMethod(sessionId: string, method: string): void {
    const session = this.sessions.get(sessionId);
    if (session) {
      session.lastMethod = method;
    }
  }
}

/** Singleton instance. */
export const sessionManager = new SessionManager();
